<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-28T15:44:54+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      misc.do_page_reindex_check
 * @group     concrete
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'version_installed' => '8.1.0',
    'version_db_installed' => '20170123000000',
    'locale' => 'fr_FR',
    'misc' => [
        'login_redirect' => 'DESKTOP',
        'access_entity_updated' => 1488297288,
        'latest_version' => '8.1.0',
        'do_page_reindex_check' => false,
    ],
    'i18n' => [
        'choose_language_login' => null,
    ],
];
