<?php

/**
 * -----------------------------------------------------------------------------
 * Generated 2017-03-01T14:56:58+00:00
 *
 * DO NOT EDIT THIS FILE DIRECTLY
 *
 * @item      sites.default.multilingual.default_source_locale
 * @group     site
 * @namespace null
 * -----------------------------------------------------------------------------
 */
return [
    'sites' => [
        'default' => [
            'name' => 'nono',
            'multilingual' => [
                'redirect_home_to_default_locale' => '1',
                'use_browser_detected_locale' => '1',
                'default_source_locale' => 'fr_FR',
            ],
        ],
    ],
];
